### ISSUE TITLE
Error: Could not load the bindings file. Tried:

### ISSUE THREAD

**Issue by owlwink** [neiltron/node-pulsesensor#4]
I have tried and tested my Arduino using Johnny-Five and have uploaded the appropriate Firmata and it works fine with other projects, but when trying to run the node in the terminal as per the instructions for this I am receiving the following error:

Error: Could not load the bindings file. Tried:
 -> /Users/jeremiahambrose/node-pulsesensor/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/build/Debug/serialport.node
 -> /Users/jeremiahambrose/node-pulsesensor/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/build/Release/serialport.node
 -> /Users/jeremiahambrose/node-pulsesensor/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/out/Debug/serialport.node
 -> /Users/jeremiahambrose/node-pulsesensor/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/Debug/serialport.node
 -> /Users/jeremiahambrose/node-pulsesensor/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/out/Release/serialport.node
 -> /Users/jeremiahambrose/node-pulsesensor/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/Release/serialport.node
 -> /Users/jeremiahambrose/node-pulsesensor/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/build/default/serialport.node
 -> /Users/jeremiahambrose/node-pulsesensor/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/compiled/5.0/darwin/x64/serialport.node
    at bindings (/Users/jeremiahambrose/node-pulsesensor/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/node_modules/bindings/bindings.js:82:13)
    at Object.<anonymous> (/Users/jeremiahambrose/node-pulsesensor/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/serialport.js:7:44)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/jeremiahambrose/node-pulsesensor/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:9:18)
    at Module._compile (module.js:425:26)

Any help you could offer with this would be greatly appreciated :-)

**Comment by neiltron** [comment]
It's been a while since I've used this, but I'll see if I can break out my pulse sensor and arduino and take a look.

**Comment by charliegerard** [comment]
I just spent some time fixing this and made a pull request :)
The main issues seemed to be with the node modules. Otherwise a few changes in the server.js file and it's all good for me now!
Hope it helps!

**Comment by neiltron** [comment]
Just merged those changes in. @owlwink let me know if you're still having trouble.
